correctif root_path + test synchronizer_current_log

diff --git a/launcher b/launcher
--- a/launcher
+++ b/launcher
@@ -4,13 +4,65 @@
 
 #Manual = 0
 
+#Exit code
+INVALID_NUMBER_OF_ARGUMENTS=1
+INVALID_ARGUMENTS=2
+
+root_path=""
+
 #pwd
 
-echo -e "\nGIT DU PAUVRE\n"
+echo -e "\nGIT MAISON LO14\n"
 
-bin/main_explorer $1 $2 0
+#number of arguments control
+if [ $# -ne 4 ]
+then
+	echo -e "invalid number of argument\n You need to use $0 path_treeA path_treeB -option(a/m) path_log"
+	exit $INVALID_NUMBER_OF_ARGUMENTS
+fi
+#$1 control
+if [[ ! -d $1 ]]
+then
+	echo -e "$1 is not a directory"
+	exit $INVALID_ARGUMENTS
+fi
+#2 control
+if [[ ! -d $2 ]]
+then
+	echo -e "$2 is not a directory"
+        exit $INVALID_ARGUMENTS
+fi
+#$3 control
+if [ $# -eq 3 ] && [ -f $3 ]
+then
+	head=$(head -n1 $3)
+	if [[ "$head" =! "synchronizer_log" ]]
+	then
+		echo "$3 is not a log file for this synchronizer"
+		exit $INVALID_ARGUMENTS
+	fi
+else
+	echo "$3 is not a log file for this synchronizer"
+        exit $INVALID_ARGUMENTS
+fi
 
-path_size_to_delete=$(echo $1 | wc -m)
-echo "" > ~/Documents/log
-bin/log_generator $1 path_size_to_delete ~/Documents/log
+#$4 control
+if [[ "$4" == "-a" -o "$4" == "-m" ]]
+then
+        echo -e "$4 is not an option for this synchronizer \ntry -a or -m "
+        exit $INVALID_ARGUMENTS
+fi
+
+#current_log initiation
+touch /tmp/synchronizer_current_log
+if [[ "$4" == "-a" ]]
+then
+	echo $3 > /tmp/synchronizer_current_log
+fi
+
+$root_path/main_explorer $1 $2
+
+path_size_to_delete=$(echo $1 | wc -m) #AJOUTER +1
+path_size_to_delete=$((path_size_to_delete+=1))
+$root_path/bin/log_generator $1 path_size_to_delete $3 
 
